name: Azure VM Setup and Deploy

on:
  push:
    branches:
      - main

jobs:
  setup-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0

      - name: Terraform Init and Apply
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          cd path/to/terraform/files # Change to the directory where your .tf files are
          terraform init
          terraform apply -auto-approve

  deploy-container:
    runs-on: ubuntu-latest
    needs: setup-infra
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Ansible Playbook
        uses: ansible/ansible-runner-action@v2
        with:
          playbook: ansible/ansible-playbook.yml
